import "server-only";

/**
 * What happened to a board task after ▶ Run (Chris, 09-09: "it should have
 * indicators after run, doesn't have to be live"). Read from GitHub when the
 * board page loads — no polling. One issues call + one comments call per
 * running task plus one PR list for all of them; the runner's PR body starts
 * with "Closes #n".
 *
 * 09-09 later: Chris wants the whole loop on cardflip ("I don't want things
 * interconnected") — so the status carries the runner's "Reading this as"
 * line, its needs-you question, the PR summary and the deploy state, and
 * the board has a Merge button (POST /api/admin/board/merge). GitHub and
 * Vercel stay underneath; he never has to open them.
 */

export const BOARD_REPO = "truefreemoney-rgb/cardflip";

export type RunState = "running" | "needs-you" | "pr-ready" | "done" | "closed";
export type DeployState = "building" | "ready" | "failed";

export interface RunStatus {
  state: RunState;
  /** Where to go: the PR when there is one, else the issue. */
  url: string;
  /** When the Run press opened the issue (ISO). */
  startedAt: string;
  /** The runner's one-line restatement of the task, once it posts it. */
  reading?: string;
  /** What the runner asked when it labelled needs-chris. */
  question?: string;
  /** The PR, once opened: number, title, and the body bullets in plain words. */
  pr?: { number: number; title: string; summary: string[]; mergedAt: string | null };
  /** After the merge: Vercel's production build of the merge commit. */
  deploy?: DeployState;
}

interface GhIssue {
  number: number;
  state: "open" | "closed";
  html_url: string;
  created_at: string;
  labels?: { name: string }[];
}
interface GhPull {
  number: number;
  title: string;
  state: "open" | "closed";
  html_url: string;
  body: string | null;
  merged_at: string | null;
  merge_commit_sha: string | null;
}
interface GhComment {
  body: string;
  created_at: string;
}
interface GhCombinedStatus {
  state: "pending" | "success" | "failure" | "error";
  total_count: number;
}

export function ghHeaders(token: string): Record<string, string> {
  return { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json", "User-Agent": "cardflip-board" };
}

async function gh<T>(path: string, token: string): Promise<T | null> {
  try {
    const res = await fetch(`https://api.github.com/repos/${BOARD_REPO}${path}`, {
      headers: ghHeaders(token),
      signal: AbortSignal.timeout(8_000),
      cache: "no-store",
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

/** Markdown → plain words for a chip: no bold/code/link syntax, no runner trailer. */
function plain(md: string): string {
  return md
    .replace(/\s*---\s*_?Generated by[\s\S]*$/i, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[*_`]+/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** The PR body as up to six short plain-text lines, skipping the "Closes #n" and the trailer. */
export function summarize(body: string | null): string[] {
  if (!body) return [];
  const lines = body
    .replace(/\s*---\s*_?Generated by[\s\S]*$/i, "")
    .replace(/https:\/\/claude\.ai\/code\/\S+/g, "")
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l && !/^closes #\d+/i.test(l) && !/^🤖/.test(l) && !/^generated (with|by)/i.test(l));
  const bullets = lines.filter((l) => /^[-*]\s+/.test(l)).map((l) => plain(l.replace(/^[-*]\s+/, "")));
  const pick = bullets.length ? bullets : lines.map(plain);
  return pick.filter(Boolean).slice(0, 6).map((l) => (l.length > 240 ? `${l.slice(0, 237)}…` : l));
}

export async function runStatuses(numbers: number[]): Promise<Record<number, RunStatus>> {
  const token = process.env.GITHUB_TOKEN;
  const out: Record<number, RunStatus> = {};
  const wanted = Array.from(new Set(numbers.filter((n) => Number.isInteger(n) && n > 0)));
  if (!token || wanted.length === 0) return out;

  const [pulls, ...rest] = await Promise.all([
    gh<GhPull[]>("/pulls?state=all&sort=created&direction=desc&per_page=50", token),
    ...wanted.flatMap((n) => [gh<GhIssue>(`/issues/${n}`, token), gh<GhComment[]>(`/issues/${n}/comments?per_page=30`, token)]),
  ]);

  const prs: (GhPull | undefined)[] = [];
  wanted.forEach((n, i) => {
    const issue = rest[i * 2] as GhIssue | null;
    const comments = (rest[i * 2 + 1] as GhComment[] | null) ?? [];
    if (!issue) return;
    // Several PRs can name the same issue (a duplicate run, a retry): the
    // merged one is the answer, else the open one, else the newest.
    const matches = (pulls ?? []).filter((p) => new RegExp(`^\\s*Closes #${n}\\b`, "i").test(p.body ?? ""));
    const pr = matches.find((p) => p.merged_at) ?? matches.find((p) => p.state === "open") ?? matches[0];
    prs[i] = pr;
    const labels = new Set((issue.labels ?? []).map((l) => l.name));
    let state: RunState = "running";
    if (pr?.merged_at) state = "done";
    else if (issue.state === "closed") state = "closed";
    else if (labels.has("needs-chris")) state = "needs-you";
    else if (pr && pr.state === "open") state = "pr-ready";

    const reading = comments.map((c) => plain(c.body)).find((b) => /^reading this as:/i.test(b));
    // The needs-you question is the runner's last comment that is not the
    // reading line or a "PR ready" pointer.
    const question =
      state === "needs-you"
        ? comments
            .map((c) => plain(c.body))
            .filter((b) => b && !/^reading this as:/i.test(b) && !/^pr ready:/i.test(b))
            .at(-1)
        : undefined;

    out[n] = {
      state,
      url: pr && state !== "needs-you" ? pr.html_url : issue.html_url,
      startedAt: issue.created_at,
      ...(reading ? { reading: reading.replace(/^reading this as:\s*/i, "") } : {}),
      ...(question ? { question } : {}),
      ...(pr ? { pr: { number: pr.number, title: pr.title, summary: summarize(pr.body), mergedAt: pr.merged_at } } : {}),
    };
  });

  // Deploy state for merged PRs: Vercel posts a commit status on the merge commit.
  await Promise.all(
    wanted.map(async (n, i) => {
      const pr = prs[i];
      const st = out[n];
      if (!st || st.state !== "done" || !pr?.merge_commit_sha) return;
      const combined = await gh<GhCombinedStatus>(`/commits/${pr.merge_commit_sha}/status`, token);
      if (!combined || combined.total_count === 0) {
        // No status yet: Vercel usually reports within a minute of the merge.
        st.deploy = "building";
        return;
      }
      st.deploy = combined.state === "success" ? "ready" : combined.state === "pending" ? "building" : "failed";
    }),
  );
  return out;
}
