import Link from "next/link";
import MarketingNav from "@/components/MarketingNav";
import DemoButton from "@/components/DemoButton";
import HeroShowcase from "@/components/HeroShowcase";
import { getFeaturedCard } from "@/lib/tcg";

const steps = [
  {
    title: "Scan the card",
    body: "Photograph the card — or drop in a whole stack. CardFlip reads the name and collector number straight off the image.",
  },
  {
    title: "Get the real price",
    body: "We match the exact printing and pull live market pricing, then adjust for the condition you pick.",
  },
  {
    title: "Post it",
    body: "Title, description and price are written for you. Review, then send it to eBay.",
  },
];

const features = [
  {
    title: "Scan a whole binder",
    body: "Queue up as many cards as you like. Each one is read, priced and written up while you keep scanning.",
  },
  {
    title: "Prices per printing",
    body: "Holo, reverse holo and 1st edition are priced separately — never averaged into a number that matches nothing.",
  },
  {
    title: "Built to sell fast",
    body: "Quick-sale pricing undercuts the market so cards actually move, or hold out for full value. Your call.",
  },
  {
    title: "Your eBay, your money",
    body: "Listings go up under your own account. You keep control, and you keep the payout.",
  },
];

const faqs = [
  {
    q: "Does it work on any Pokémon card?",
    a: "Any card in the Pokémon TCG catalog, from Base Set to the current sets. If a scan doesn't match, you can search by name and pick the right printing in a couple of seconds.",
  },
  {
    q: "How accurate is the pricing?",
    a: "Prices come from live TCGplayer and Cardmarket market data for the exact printing, then get adjusted for the condition you select. Condition multipliers are estimates to anchor your listing, not a formal appraisal.",
  },
  {
    q: "Do I need my own eBay account?",
    a: "Yes. CardFlip creates the listing content and hands it to eBay under your account, so payouts and buyer messages come straight to you.",
  },
  {
    q: "What does it cost?",
    a: "Free while we're in early access. You only pay eBay's own selling fees.",
  },
];

export default async function Home() {
  const featured = await getFeaturedCard();

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <MarketingNav />

      <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col">
        <section className="relative flex flex-col items-center gap-6 px-6 pb-16 pt-20 text-center sm:pt-28">
          <div
            className="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[min(90vw,560px)] -translate-x-1/2 -translate-y-1/3 rounded-full bg-brand-600/20 blur-3xl"
            aria-hidden
          />

          <div className="animate-fade-up relative inline-flex items-center gap-2 rounded-full border border-edge bg-surface-1 px-4 py-1.5 text-xs font-medium text-zinc-300">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
            Early access · free while in beta
          </div>

          <h1
            className="animate-fade-up relative max-w-3xl text-4xl font-semibold sm:text-6xl"
            style={{ animationDelay: "60ms" }}
          >
            Sell your Pokémon cards
            <br />
            <span className="bg-gradient-to-r from-brand-300 via-brand-400 to-violet-400 bg-clip-text text-transparent">
              without the busywork.
            </span>
          </h1>

          <p
            className="animate-fade-up relative max-w-xl text-lg leading-relaxed text-zinc-400"
            style={{ animationDelay: "120ms" }}
          >
            Scanning a card takes a second. Pricing it, writing the listing and
            getting it online takes ten minutes. CardFlip does the other nine.
          </p>

          <div
            className="animate-fade-up relative mt-2 flex flex-col gap-3 sm:flex-row"
            style={{ animationDelay: "180ms" }}
          >
            <Link
              href="/signup"
              className="rounded-full bg-brand-500 px-7 py-3.5 text-sm font-semibold text-white shadow-lg shadow-brand-500/25 transition hover:-translate-y-0.5 hover:bg-brand-400"
            >
              Start selling free
            </Link>
            <DemoButton />
          </div>
        </section>

        {featured && (
          <section className="px-6 pb-24">
            <HeroShowcase card={featured} />
            <p className="mt-6 text-center text-xs text-zinc-600">
              Live example — real card, real market price, generated by CardFlip.
            </p>
          </section>
        )}

        <section id="how-it-works" className="scroll-mt-20 px-6 py-16">
          <h2 className="text-center text-sm font-semibold uppercase tracking-widest text-brand-400">
            How it works
          </h2>
          <div className="relative mt-10 grid gap-6 sm:grid-cols-3">
            <div
              className="pointer-events-none absolute left-0 right-0 top-10 hidden h-px bg-gradient-to-r from-transparent via-white/10 to-transparent sm:block"
              aria-hidden
            />
            {steps.map((step, i) => (
              <div
                key={step.title}
                className="relative rounded-2xl border border-edge bg-background p-6"
              >
                <div className="mb-4 flex h-9 w-9 items-center justify-center rounded-full bg-brand-500/15 text-sm font-semibold text-brand-300">
                  {i + 1}
                </div>
                <h3 className="text-base font-semibold text-white">
                  {step.title}
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-zinc-400">
                  {step.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section className="px-6 py-16">
          <h2 className="text-center text-sm font-semibold uppercase tracking-widest text-brand-400">
            Why CardFlip
          </h2>
          <div className="mt-8 grid gap-4 sm:grid-cols-2">
            {features.map((f) => (
              <div
                key={f.title}
                className="rounded-2xl border border-edge bg-surface-1 p-6 transition hover:border-edge-strong hover:bg-surface-2"
              >
                <h3 className="text-base font-semibold text-white">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-zinc-400">
                  {f.body}
                </p>
              </div>
            ))}
          </div>
        </section>

        <section className="px-6 py-16">
          <h2 className="text-center text-sm font-semibold uppercase tracking-widest text-brand-400">
            Questions
          </h2>
          <div className="mx-auto mt-8 max-w-2xl divide-y divide-white/5 overflow-hidden rounded-2xl border border-edge bg-surface-1">
            {faqs.map((faq) => (
              <details key={faq.q} className="group px-5 py-4">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium text-white marker:content-none">
                  {faq.q}
                  <span
                    className="shrink-0 text-zinc-500 transition-transform group-open:rotate-45"
                    aria-hidden
                  >
                    +
                  </span>
                </summary>
                <p className="mt-3 text-sm leading-relaxed text-zinc-400">
                  {faq.a}
                </p>
              </details>
            ))}
          </div>
        </section>

        <section className="px-6 py-20">
          <div className="relative mx-auto flex max-w-2xl flex-col items-center gap-5 overflow-hidden rounded-3xl border border-edge bg-gradient-to-b from-surface-2 to-transparent p-12 text-center">
            <div
              className="pointer-events-none absolute left-1/2 top-0 h-64 w-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-brand-500/20 blur-3xl"
              aria-hidden
            />
            <h2 className="relative text-2xl font-semibold text-white sm:text-3xl">
              Ready to clear out your binder?
            </h2>
            <p className="relative text-zinc-400">
              Create your free account and connect eBay to start listing.
            </p>
            <Link
              href="/signup"
              className="relative rounded-full bg-brand-500 px-7 py-3.5 text-sm font-semibold text-white shadow-lg shadow-brand-500/25 transition hover:-translate-y-0.5 hover:bg-brand-400"
            >
              Get started
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t border-white/5 px-6 py-8">
        <div className="mx-auto flex w-full max-w-6xl flex-col items-center justify-between gap-3 text-xs text-zinc-600 sm:flex-row">
          <span>© {new Date().getFullYear()} CardFlip</span>
          <span className="text-center">
            Not affiliated with Nintendo, The Pokémon Company, or eBay Inc.
          </span>
        </div>
      </footer>
    </div>
  );
}
