/**
 * docs/BOARD.md parser (lib/server/board.ts). Run: npm run test:board
 * Pins the shape the admin console relies on, and that the real file parses
 * into non-empty sections with owner tags.
 */
import { readFileSync } from "node:fs";
const { parseBoard, serializeBoard, validateBoard } = await import(new URL("../src/lib/server/board.ts", import.meta.url).href);

let failures = 0;
function check(label, actual, expected) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (!ok) failures++;
  console.log(`  ${ok ? "PASS" : "FAIL"}  ${label}${ok ? "" : `\n         got      ${JSON.stringify(actual)}\n         expected ${JSON.stringify(expected)}`}`);
}

const sample = `# Board\nintro\n\n## Now — current main tasks\n- [ ] [Chris] Do the thing\n- [x] [Claude] Done **bold** thing\n\n## Future ideas\n- [ ] Untagged idea\n`;
const s = parseBoard(sample);
check("two sections", s.map((x) => x.title), ["Now", "Future ideas"]);
check("hint after the dash", s[0].hint, "current main tasks");
const strip = ({ id, ...rest }) => rest;
check("owner tag + text", strip(s[0].items[0]), { done: false, owner: "Chris", text: "Do the thing" });
check("done + bold stripped", strip(s[0].items[1]), { done: true, owner: "Claude", text: "Done bold thing" });
check("untagged item", strip(s[1].items[0]), { done: false, owner: null, text: "Untagged idea" });
check("ids are unique", new Set(s.flatMap((x) => [x.id, ...x.items.map((i) => i.id)])).size, 5);

// Round trip: serialize → parse gives the same content back.
const again = parseBoard(serializeBoard(s));
check("round trip keeps sections + items", again.map((x) => [x.title, x.hint, x.items.map(strip)]), s.map((x) => [x.title, x.hint, x.items.map(strip)]));

// Validation: what the admin console PUTs.
const v = validateBoard(s);
check("valid board passes", v.ok, true);
check("trims + keeps content", v.ok && v.sections[0].items[0].text, "Do the thing");
check("rejects non-array", validateBoard({}).ok, false);
check("rejects empty title", validateBoard([{ id: "a", title: " ", hint: null, items: [] }]).ok, false);
check("rejects bad owner", validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: "Bob", text: "x" }] }]).ok, false);
check("rejects duplicate ids", validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "a", done: false, owner: null, text: "x" }] }]).ok, false);
check("rejects bad id chars", validateBoard([{ id: "a b", title: "T", hint: null, items: [] }]).ok, false);
check("empty hint becomes null", validateBoard([{ id: "a", title: "T", hint: "  ", items: [] }]).sections?.[0].hint, null);

// Photos on notes (09-09): only our Blob store, at most 6, empty list dropped.
const BLOB = "https://abc123.public.blob.vercel-storage.com/board/x-1.jpg";
check("keeps blob image urls", validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: null, text: "x", images: [BLOB] }] }]).sections?.[0].items[0].images?.[0], BLOB);
check("rejects off-site image urls", validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: null, text: "x", images: ["https://evil.example/x.jpg"] }] }]).ok, false);
check("rejects 7 images", validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: null, text: "x", images: Array(7).fill(BLOB) }] }]).ok, false);
check("empty images list is dropped", "images" in validateBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: null, text: "x", images: [] }] }]).sections[0].items[0], false);
check("serialize appends image links", serializeBoard([{ id: "a", title: "T", hint: null, items: [{ id: "b", done: false, owner: null, text: "x", images: [BLOB] }] }]).includes(`x [image](${BLOB})`), true);

// Run panel on the board (09-09): the PR body in plain words.
const { summarize } = await import(new URL("../src/lib/server/boardRuns.ts", import.meta.url).href);
const prBody = [
  "Closes #9",
  "",
  "- **Gyarados leaves** the stage — see `stageCards.ts`.",
  "- Price target $50 → $35 ([why](https://x.y)).",
  "",
  "🤖 Generated with Claude Code",
  "",
  "---",
  "_Generated by [Claude Code](https://claude.ai)_",
].join("\n");
check("summarize keeps the bullets, drops Closes and trailers", JSON.stringify(summarize(prBody)), JSON.stringify(["Gyarados leaves the stage — see stageCards.ts.", "Price target $50 → $35 (why)."]));
check("summarize of empty body", summarize(null).length, 0);

// Completed sweep (09-09): done items move to Completed (stamped), un-ticked ones go home.
const { normalizeBoard } = await import(new URL("../src/lib/server/board.ts", import.meta.url).href);
const swept = normalizeBoard(
  [
    { id: "now", title: "Now", hint: null, items: [{ id: "a", done: true, owner: "Claude", text: "shipped" }, { id: "b", done: false, owner: null, text: "open" }] },
    { id: "c", title: "Completed", hint: null, items: [{ id: "old", done: true, owner: null, text: "older", completedAt: 5, from: "Now" }, { id: "re", done: false, owner: null, text: "reopen me", completedAt: 4, from: "Now" }] },
  ],
  1000,
);
check("sweep moved the done item out of Now", swept.sections[0].items.map((i) => i.id).join(","), "b,re");
check("sweep put it on top of Completed, stamped", JSON.stringify(swept.sections[1].items.map((i) => [i.id, i.completedAt, i.from])), JSON.stringify([["a", 1000, "Now"], ["old", 5, "Now"]]));
check("reopened item lost its stamp", "completedAt" in swept.sections[0].items[1], false);
check("sweep reports change", swept.changed, true);
check("sweep is idempotent", normalizeBoard(swept.sections, 2000).changed, false);

const real = parseBoard(readFileSync(new URL("../docs/BOARD.md", import.meta.url), "utf8"));
check("real board has the core categories", ["Now", "Chris", "Claude", "Future ideas"].every((t) => real.some((x) => x.title === t)), true);
check("every OPEN real item carries an owner tag", real.flatMap((x) => x.items).filter((i) => !i.done).every((i) => i.owner !== null), true);

console.log(failures === 0 ? "\nAll board checks passed." : `\n${failures} board check(s) FAILED.`);
process.exitCode = failures === 0 ? 0 : 1;
